'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient, US_STATES } from '@/lib/supabase'
import { generateDisplayName, savePendingSignup } from '@/lib/onboarding'

export default function SignupPage() {
  const [email, setEmail] = useState('')
  const [stateCode, setStateCode] = useState('')
  const [displayName, setDisplayName] = useState('LibertyLifter1776')
  const [loadingProvider, setLoadingProvider] = useState<'google' | 'email' | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [emailSent, setEmailSent] = useState(false)
  const supabase = createClient()

  const selectedState = stateCode ? US_STATES[stateCode] : null
  const redirectTo = typeof window === 'undefined'
    ? undefined
    : `${window.location.origin}/auth/callback?next=/dashboard`

  useEffect(() => {
    setDisplayName(generateDisplayName(stateCode))
  }, [stateCode])

  const persistPendingSignup = () => {
    if (!stateCode) return
    savePendingSignup({
      displayName,
      stateCode,
    })
  }

  const handleGoogleSignup = async () => {
    if (!stateCode) {
      setError('Choose your state first.')
      return
    }

    setError(null)
    setEmailSent(false)
    setLoadingProvider('google')
    persistPendingSignup()

    const { error: oauthError } = await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: {
        redirectTo,
      },
    })

    if (oauthError) {
      setError(oauthError.message)
      setLoadingProvider(null)
    }
  }

  const handleEmailSignup = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!stateCode) {
      setError('Choose your state first.')
      return
    }

    setError(null)
    setEmailSent(false)
    setLoadingProvider('email')
    persistPendingSignup()

    const { error: otpError } = await supabase.auth.signInWithOtp({
      email: email.trim().toLowerCase(),
      options: {
        emailRedirectTo: redirectTo,
        data: {
          display_name: displayName,
          state_code: stateCode,
        },
      },
    })

    if (otpError) {
      setError(otpError.message)
      setLoadingProvider(null)
      return
    }

    setEmailSent(true)
    setLoadingProvider(null)
  }

  return (
    <main className="auth-page">
      <header className="conversion-nav">
        <Link href="/" className="flex items-center gap-3 campaign-nav-mark">
          <span className="campaign-nav-monogram">LL</span>
          <span className="campaign-nav-name">Liberty Lift / 1776</span>
        </Link>

        <div className="conversion-nav-actions">
          <Link href="/login" className="conversion-signin">
            Sign in
          </Link>
        </div>
      </header>

      <section className="auth-shell">
        <div className="auth-copy">
          <div className="app-eyebrow mb-4">Join your state</div>
          <h1 className="app-title auth-title">
            1,776 push-ups.
            <br />
            <em>One team.</em>
          </h1>
          <p>
            Pick your state, grab an autogenerated handle, and get your dashboard.
            You can edit the handle later.
          </p>
        </div>

        <div className="auth-card">
          <div className="auth-step-label">Step 1</div>
          <label className="auth-label" htmlFor="state-code">
            Choose your state
          </label>
          <select
            id="state-code"
            value={stateCode}
            onChange={(event) => {
              setStateCode(event.target.value)
              setError(null)
              setEmailSent(false)
            }}
            className="input bg-white/5"
          >
            <option value="">Select your state...</option>
            {Object.entries(US_STATES).map(([code, name]) => (
              <option key={code} value={code}>
                {name}
              </option>
            ))}
          </select>

          <div className="generated-handle" aria-live="polite">
            <span>Your public handle</span>
            <strong>{displayName}</strong>
          </div>

          {selectedState && (
            <div className="state-join-callout">
              You are joining Team {selectedState}. Every rep you log moves your state total.
            </div>
          )}

          <div className="auth-step-label auth-step-gap">Step 2</div>
          <button
            type="button"
            onClick={handleGoogleSignup}
            disabled={!stateCode || loadingProvider !== null}
            className="auth-google-button"
          >
            <span aria-hidden="true">G</span>
            {loadingProvider === 'google' ? 'Opening Google...' : 'Continue with Google'}
          </button>

          <div className="auth-divider">
            <span>or use email</span>
          </div>

          <form onSubmit={handleEmailSignup} className="auth-email-form">
            <label className="auth-label" htmlFor="email">
              Email
            </label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(event) => {
                setEmail(event.target.value)
                setError(null)
                setEmailSent(false)
              }}
              className="input"
              placeholder="you@example.com"
              required
            />

            <button
              type="submit"
              disabled={!stateCode || loadingProvider !== null}
              className="btn-gold w-full py-3 disabled:opacity-50"
            >
              {loadingProvider === 'email' ? 'Sending link...' : 'Email me a sign-in link'}
            </button>
          </form>

          {emailSent && (
            <div className="auth-success" role="status">
              Check your email for the sign-in link. Your state and handle are waiting.
            </div>
          )}

          {error && (
            <div className="auth-error" role="alert">
              {error}
            </div>
          )}

          <p className="auth-footnote">
            No password required. Already joined?{' '}
            <Link href="/login" className="text-liberty-gold hover:underline">
              Sign in
            </Link>
          </p>
        </div>
      </section>
    </main>
  )
}
